---
version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile

    command: "runserver 0.0.0.0:8000"
    entrypoint: "./manage.py"
    environment:
      PYTHONUNBUFFERED: 0
      DJANGO_SETTINGS_MODULE: feinstaub.settings.base

    volumes:
      - "./:/opt/code"

    ports:
      - "8000:8000"

  db:
    image: postgres:9.6
