---
name: Continuous Integration
on:
  push: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: install poetry
        run: |
          python -m pip install --no-cache-dir poetry

      - name: disable virtuelenvs
        run: |
          poetry config virtualenvs.create false

      - name: clone repository
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          poetry install --no-interaction

      - name: run nox
        run: |
          poetry run nox
